### ISSUE TITLE
Unable to install on Ubuntu 12.04 using ROS Groovy and Hydro

### ISSUE THREAD

**Issue by Seanny123** [ipa320/cob_people_perception#11]
Due to the lack of a README, this package is a little confusing to install. Based on [this wiki](http://wiki.ros.org/cob_people_detection?distro=electric), I know I have to clone your repository and build the package.

I've cloned the repository using `git clone https://github.com/ipa320/cob_people_perception.git`.
I then created a directory called build `cd cob_people_perception && mkdir build && cd build`
I then started Cmake `cmake ..` and then `sudo make ..` and desperately `sudo make install`, but launching the service (after launching openni of course) with `roslaunch cob_people_detection people_detection.launch` failed.

It then tried again without making the build directory `cmake .` and `sudo make` and desperately `sudo make install`, but launching the service still failed.

Judging by the output of `make -d` there doesn't seem to be any obvious errors.

By failed, I mean that got the error message `[people_detection.launch] is neither a launch file in package [cob_people_detection] nor is [cob_people_detection] a launch file name`, even after attempting `rosintall cob_people_detection /opt/ros/groovy`.

If you could make a quick plain text README, it would be greatly appreciated. I would even submit a pull request to format it and expand on it!

**Comment by Seanny123** [comment]
I found a co-worker that helped me with installing ROS packages. He showed me that you need to add the file path into your `~/.bashrc` and you need to use `rosmake`. After following his instructions, I found out the package had an unmet dependency which is `cob_perception_common`, which I installed successfully, but you should really have that dependency listed in the make file. I'll make a pull request once I get this thing working.

With that dependency installed, when I run `rosmake`, I get the following error:

```
[ 86%] Building CXX object CMakeFiles/detection_tracker_node.dir/ros/src/detection_tracker_node.cpp.o
CMakeFiles/coordinator_node.dir/ros/src/coordinator_node.cpp.o: In function `boost::thread::join()':
/usr/local/include/boost/thread/detail/thread.hpp:756: undefined reference to `boost::thread::join_noexcept()'
CMakeFiles/coordinator_node.dir/ros/src/coordinator_node.cpp.o: In function `boost::thread::start_thread()':
/usr/local/include/boost/thread/detail/thread.hpp:180: undefined reference to `boost::thread::start_thread_noexcept()'
collect2: ld returned 1 exit status
make[3]: *** [../bin/coordinator_node] Error 1
make[3]: Leaving directory `/home/koji/Sean/cob_people_perception/cob_people_detection/build'
```

Which I think means there is a problem with the libraries your are linking to in `CMakeList.txt`. I will create a pull request once I find them.

**Comment by Seanny123** [comment]
Resolved in the new pull request I created.

**Comment by ipa-rmb** [comment]
Hi Sean,

the dependency you are referring to in your second comment is contained in the cob_people_detection/manifest.xml file as 
  depend package="cob_vision_utils"
  depend package="cob_image_flip"
as well as in the stack.xml file on the top-level directory as
  depend stack="cob_perception_common" 

This is the way those references are made explicit in ROS, so an entry is not necessary in the make file. This may be quite uncommon to new ROS users but I understood this is how is is done. You will probably see the same proceeding in many other ROS packages as well.

Best regards,
Richard

**Comment by Seanny123** [comment]
Yes, I figured all of that out eventually and reflected it in my pull request. Thank you for your time Richard.

**Comment by ipa-rmb** [comment]
Oh yes, I just read about it. Sorry that I could not answer before. However, I think there are still some things not completely in the right way in your current readme, but I will fix it in a couple of minutes.
