### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Seanny123** [ipa320/cob_people_perception#18]
Whenever I run this package with ROS, I notice a surprisingly high CPU usage, regardless of the frequency of the message gateway that I select. For example, at 5 Hz, I see a CPU usage of around 85% for my 4 cores of my Intel® Core™2 Quad CPU Q9650 @ 3.00GHz.  I have a GeForce GTX 285 as my GPU, so I'm assuming this would take most of the load off the processing anyways, but I can't confirm for sure since there is no way for me to monitor my GPU usage.

![cpu_5hz](https://f.cloud.github.com/assets/1918825/1520160/d8fcc06a-4b74-11e3-87e0-c8597c5e8acc.png)

Is this expected or is this an indication that there is something wrong with my installation? Alternatively, if it is expected, is there anything I can help out that is being investigated that might bring the usage down?

**Comment by Seanny123** [comment]
Changed to a system with a Intel® Core™ i7-2600K CPU @ 3.40GHz × 8 processor. It used all the 8 cores to around 50%. So it's consistent across installations.

**Comment by ipa-rmb** [comment]
Hi Sean, the measurements might be correct as they are similarly high at 5Hz on my laptop I7 M640. The benefit of throttling the camera rate, however, has not yet been tested. It might be the case that the Kinect driver, which is always outputting images with 30Hz, already consumes quite a bit of processing power. You may compare this by starting the Kinect driver and Rviz only and displaying the colored and registered pointcloud in Rviz.
By the way, we do not use any GPU acceleration, mainly because our robot pcs so far did not have a powerful GPU.

**Comment by ipa-rmb** [comment]
Anyways, we are currently working on some speed optimizations, which might be available during the beginning of next year. Actually, the detection phase for heads and color faces consumes most of the computational power and the Kinect driver potentially does so as well.

**Comment by ipa-rmb** [comment]
Just an update from our side: we tested the full system on a i72600K system an found varying levels of CPU usage proportional to the chosen target frame rate. See below for frame rates 1, 3, 5, 20, 30 and 100Hz.

![1fps](https://f.cloud.github.com/assets/646826/2207064/4132a28e-996e-11e3-8f08-50ffc3542c26.png)
![3fps](https://f.cloud.github.com/assets/646826/2207065/41347140-996e-11e3-8c74-1c3daf4458c3.png)
![5fps](https://f.cloud.github.com/assets/646826/2207063/41317fc6-996e-11e3-9f9b-c5bc11bc9a62.png)
![20fps](https://f.cloud.github.com/assets/646826/2207068/413818e0-996e-11e3-9cfd-d866ad45728e.png)
![30fps](https://f.cloud.github.com/assets/646826/2207067/4135b410-996e-11e3-93f9-54aaf64b8f48.png)
![100fps](https://f.cloud.github.com/assets/646826/2207066/4134e17a-996e-11e3-833f-fc8e14a3cc78.png)
