### ISSUE TITLE
I get an error says non-existent package 'kdl'

### ISSUE THREAD

**Issue by max90727** [ipa320/cob_people_perception#20]
I made the ros_package "cob_people_detection" in groovy and I got an error.

[rospack] Error: package/stack 'cob_people_detection' depends on non-existent package 'kdl' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'

CMake Error at /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:129 (message):

Failed to invoke rospack to get compile flags for package
'cob_people_detection'.  Look above for errors from rospack itself.
Aborting.  Please fix the broken dependency!

Call Stack (most recent call first):
/opt/ros/groovy/share/ros/core/rosbuild/public.cmake:203 (rosbuild_invoke_rospack)
CMakeLists.txt:16 (rosbuild_init)

I have already installed the ros-groovy-kdl, but the error still exist. WHY?

**Comment by ipa-rmb** [comment]
Thanks for your pull request. Apparently some packages have changed in the meantime. I will verify why kdl this is needed at all as it does not immediately come to my mind why we needed kinematics with people perception. Maybe it was introduced by accident.

**Comment by ipa-rmb** [comment]
I have tested everything with your suggested changes and it works well with the new dependencies. Thanks for your help!
