### ISSUE TITLE
Error during catkin_make

### ISSUE THREAD

**Issue by robotsorcerer** [ipa320/cob_people_perception#26]
Hi 

I've been trying to compile the cob_people_perception code but I keep running into errors:

> lex@lex:~/Downloads$ cd ~/catkin_ws/ && catkin_make -DCMAKE_BUILD_TYPE="Release"
> Base path: /home/lex/catkin_ws
> Source space: /home/lex/catkin_ws/src
> Build space: /home/lex/catkin_ws/build
> Devel space: /home/lex/catkin_ws/devel
> Install space: /home/lex/catkin_ws/install
> #### 
> #### Running command: "cmake /home/lex/catkin_ws/src -DCMAKE_BUILD_TYPE=Release -DCATKIN_DEVEL_PREFIX=/home/lex/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/lex/catkin_ws/install -G Unix Makefiles" in "/home/lex/catkin_ws/build"
> #### 
> 
> -- Using CATKIN_DEVEL_PREFIX: /home/lex/catkin_ws/devel
> -- Using CMAKE_PREFIX_PATH: /home/lex/catkin_ws/src/cob_people_perception
> -- Using PYTHON_EXECUTABLE: /usr/bin/python
> -- Using Debian Python package layout
> -- Using empy: /usr/bin/empy
> -- Using CATKIN_ENABLE_TESTING: ON
> -- Call enable_testing()
> -- Using CATKIN_TEST_RESULTS_DIR: /home/lex/catkin_ws/build/test_results
> -- Found gtest sources under '/usr/src/gtest': gtests will be built
> -- Using Python nosetests: /usr/bin/nosetests-2.7
> -- catkin 0.6.14
> -- BUILD_SHARED_LIBS is on
> -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> -- ~~  traversing 13 packages in topological order:
> -- ~~  - cob_people_detection
> -- ~~  - cob_people_perception (metapackage)
> -- ~~  - cob_people_tracking_filter
> -- ~~  - cob_leg_detection
> -- ~~  - face_recognition
> -- ~~  - iai_kinect2 (metapackage)
> -- ~~  - kinect2_registration
> -- ~~  - kinect2_bridge
> -- ~~  - kinect2_calibration
> -- ~~  - kinect2_viewer
> -- ~~  - libnite2
> -- ~~  - cob_openni2_tracker
> -- ~~  - usb_cam
> -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> -- +++ processing catkin package: 'cob_people_detection'
> -- ==> add_subdirectory(cob_people_perception/cob_people_detection)
> -- Using these message generators: 
> -- Boost version: 1.54.0
> -- Found the following Boost libraries:
> --   signals
> --   system
> --   filesystem
> -- Generating .msg files for action cob_people_detection/addData /home/lex/catkin_ws/src/cob_people_perception/cob_people_detection/action/addData.action
> -- Generating .msg files for action cob_people_detection/deleteData /home/lex/catkin_ws/src/cob_people_perception/cob_people_detection/action/deleteData.action
> -- Generating .msg files for action cob_people_detection/getDetections /home/lex/catkin_ws/src/cob_people_perception/cob_people_detection/action/getDetections.action
> -- Generating .msg files for action cob_people_detection/loadModel /home/lex/catkin_ws/src/cob_people_perception/cob_people_detection/action/loadModel.action
> -- Generating .msg files for action cob_people_detection/updateData /home/lex/catkin_ws/src/cob_people_perception/cob_people_detection/action/updateData.action
> CMake Error at /opt/ros/indigo/share/genmsg/cmake/genmsg-extras.cmake:268 (message):
>   Could not find 'share/std_msgs/cmake/std_msgs-msg-paths.cmake' (searched in
>   '/home/lex/catkin_ws/devel').
> Call Stack (most recent call first):
>   cob_people_perception/cob_people_detection/CMakeLists.txt:87 (generate_messages)
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/lex/catkin_ws/build/CMakeFiles/CMakeOutput.log".
> See also "/home/lex/catkin_ws/build/CMakeFiles/CMakeError.log".
> Invoking "cmake" failed

Could you help me look into the error log please?
Thank you!

**Comment by robotsorcerer** [comment]
Curiosa & curiosa. 

I cloned 
             `cob_perception_common` 
as in 
              `git clone https://github.com/ipa-rmb/cob_perception_common.git`, 
cloned 
              `git clone https://github.com/ipa320/cob_common.git`, 
`cd`'ed into the respective folders and did `catkin_ws$ rosdep install -r --from-paths .` for each folder cloned before doing `catkin_make -DCMAKE_BUILD_TYPE="Release"` and everything was honky-dory. 

I wish you guys had a detailed README.md file that explicitly explained the installation process.

Thanks anyway!

**Comment by ipa-rmb** [comment]
Hi, sorry for the trouble you had with the installation. It seems that some standard packages (like std_msgs) have been missing. The readme.md assumes that these ROS basics are installed and so far nobody reported such problems.

Thanks a lot for providing hints on how to improve documentation. I will update the readme soon. I hope the software will be useful to you.

Best regards,
Richard

**Comment by robotsorcerer** [comment]
No worries! Just a question I have further. Does it work with the Kinect for Windows v2 sensor? Did you ever test it on it?

**Comment by ipa-rmb** [comment]
We have not tested it yet with the new Kinect, but basically we just need RGB-D data and the program should be capable of adapting to any data/sensor. At least, I have tried out to decrease the image resolution if the old Kinect and it still worked. But please let me know if you should encounter any problems, then we will fix them.

**Comment by robotsorcerer** [comment]
Well, it doesn't run on my K4W. I'm assuming this code uses the `libfreenect` driver rather than the `libfreenect2` driver which K4W uses as an open-source library?

Here is my log:

> lex@lex:~/catkin_ws$ roslaunch openni_launch openni.launch
> ... logging to /home/lex/.ros/log/d57a703c-1c23-11e5-9b63-801934199d44/roslaunch-lex-14818.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://lex:41502/
> 
> # SUMMARY
> 
> PARAMETERS
> - /camera/camera_nodelet_manager/num_worker_threads: 4
> - /camera/depth_rectify_depth/interpolation: 0
> - /camera/depth_registered_rectify_depth/interpolation: 0
> - /camera/disparity_depth/max_range: 4.0
> - /camera/disparity_depth/min_range: 0.5
> - /camera/disparity_registered_hw/max_range: 4.0
> - /camera/disparity_registered_hw/min_range: 0.5
> - /camera/disparity_registered_sw/max_range: 4.0
> - /camera/disparity_registered_sw/min_range: 0.5
> - /camera/driver/depth_camera_info_url: 
> - /camera/driver/depth_frame_id: /camera_depth_opt...
> - /camera/driver/depth_registration: False
> - /camera/driver/device_id: #1
> - /camera/driver/rgb_camera_info_url: 
> - /camera/driver/rgb_frame_id: /camera_rgb_optic...
> - /rosdistro: indigo
> - /rosversion: 1.11.13
> 
> NODES
>   /camera/
>     camera_nodelet_manager (nodelet/nodelet)
>     debayer (nodelet/nodelet)
>     depth_metric (nodelet/nodelet)
>     depth_metric_rect (nodelet/nodelet)
>     depth_points (nodelet/nodelet)
>     depth_rectify_depth (nodelet/nodelet)
>     depth_registered_rectify_depth (nodelet/nodelet)
>     disparity_depth (nodelet/nodelet)
>     disparity_registered_hw (nodelet/nodelet)
>     disparity_registered_sw (nodelet/nodelet)
>     driver (nodelet/nodelet)
>     points_xyzrgb_hw_registered (nodelet/nodelet)
>     points_xyzrgb_sw_registered (nodelet/nodelet)
>     rectify_color (nodelet/nodelet)
>     rectify_ir (nodelet/nodelet)
>     rectify_mono (nodelet/nodelet)
>     register_depth_rgb (nodelet/nodelet)
>   /
>     camera_base_link (tf/static_transform_publisher)
>     camera_base_link1 (tf/static_transform_publisher)
>     camera_base_link2 (tf/static_transform_publisher)
>     camera_base_link3 (tf/static_transform_publisher)
> 
> auto-starting new master
> process[master]: started with pid [14830]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to d57a703c-1c23-11e5-9b63-801934199d44
> process[rosout-1]: started with pid [14843]
> started core service [/rosout]
> process[camera/camera_nodelet_manager-2]: started with pid [14860]
> process[camera/driver-3]: started with pid [14861]
> [ INFO] [1435337593.896914461]: Initializing nodelet with 4 worker threads.
> process[camera/debayer-4]: started with pid [14897]
> process[camera/rectify_mono-5]: started with pid [14911]
> process[camera/rectify_color-6]: started with pid [14925]
> [ INFO] [1435337593.950430799]: No devices connected.... waiting for devices to be connected
> process[camera/rectify_ir-7]: started with pid [14940]
> process[camera/depth_rectify_depth-8]: started with pid [14954]
> process[camera/depth_metric_rect-9]: started with pid [14968]
> process[camera/depth_metric-10]: started with pid [14982]
> process[camera/depth_points-11]: started with pid [15005]
> process[camera/register_depth_rgb-12]: started with pid [15021]
> process[camera/points_xyzrgb_sw_registered-13]: started with pid [15035]
> process[camera/depth_registered_rectify_depth-14]: started with pid [15049]
> process[camera/points_xyzrgb_hw_registered-15]: started with pid [15063]
> process[camera/disparity_depth-16]: started with pid [15077]
> process[camera/disparity_registered_sw-17]: started with pid [15091]
> process[camera/disparity_registered_hw-18]: started with pid [15105]
> process[camera_base_link-19]: started with pid [15119]
> process[camera_base_link1-20]: started with pid [15130]
> process[camera_base_link2-21]: started with pid [15141]
> process[camera_base_link3-22]: started with pid [15152]
> [ INFO] [1435337596.950696666]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337599.950928354]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337602.951163758]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337605.951360944]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337608.951592861]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337611.951846516]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337614.952108442]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337617.952352160]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337620.952548463]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337623.952778447]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337626.953020924]: No devices connected.... waiting for devices to be connected
> [ INFO] [1435337629.953232781]: No devices connected.... waiting for devices to be connected

**Comment by ipa-rmb** [comment]
Well, I guess you cannot use the very old openni driver (roslaunch openni_launch openni.launch) for the new model. That driver even does not work anymore with the newer Asus cameras.

But you are right that you need the driver building on freenect2, see e.g. http://www.ros.org/news/2014/09/microsoft-kinect-v2-driver-released.html . If you are using that ROS driver, your camera should work. Once your camera is delivering data, the people detection algorithm will work similarly as with the older Kinect sensors.

**Comment by ipa-rmb** [comment]
By the way, please update the cob_people_detection code with the newest github version. An update in cob_perception_common made cob_people_detection inoperable without my newest update.

**Comment by robotsorcerer** [comment]
How do you mean that I should update the code?

**Comment by ipa-rmb** [comment]
Just
git pull origin indigo_dev
in your cob_people_detection folder again (or similar). I.e. pull the latest code from my git repository to your computer.

**Comment by robotsorcerer** [comment]
I did pull the latest `indigo_dev` files.. And I ran the `Kinect2_bridge` api before launching `cob_people_detection`. It throws out a window showing an empty image but it doens't publish frames. I might just have to build one from scratch myself.

**Comment by ipa-rmb** [comment]
Did you adapt the topics in people_detection.launch to your camera as said in the tutorial? What are the rgb and point cloud topic names in your case?

**Comment by robotsorcerer** [comment]
I did not adapt the topics. Here are the cloud topics I am using at the moment.

```
kinect2_viewer [options]
  name: 'any string' equals to the kinect2_bridge topic base name
  mode: 'qhd', 'hd', 'sd' or 'ir'
  visualization: 'image', 'cloud' or 'both'
  options:
    'compressed' use compressed instead of raw topics
    'approx' use approximate time synchronization

Example: rosrun kinect2_viewer kinect2_viewer kinect2 sd cloud
```

**Comment by robotsorcerer** [comment]
I have adapted the topics in ros/launch/people_detection.launch as I have enumerated [here](https://gist.github.com/lakehanne/8aaa7a233feaa078c3bf).
 but I am still facing the issues. I made the change according to the kinect2_bridge topics in [code-iai](https://github.com/code-iai/iai_kinect2/blob/master/kinect2_bridge/launch/kinect2_bridge.launch). One thing that I find striking is that [code-iai](https://github.com/code-iai/iai_kinect2/blob/master/kinect2_bridge/launch/kinect2_bridge.launch) doesn't appear to be using openni drivers at all as `roslaunch openni2_launch openni2.launch` gives 

> [ INFO] [1436290268.737020406]: No matching device found.... waiting for devices. Reason: std::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /tmp/buildd/ros-indigo-openni2-camera-0.2.4-0trusty-20150523-0924/src/openni2_driver.cpp @ 624 : Invalid device number 1, there are 0 devices connected.
> [ INFO] [1436290271.737328283]: No matching device found.... waiting for devices. Reason: std::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /tmp/buildd/ros-indigo-openni2-camera-0.2.4-0trusty-20150523-0924/src/openni2_driver.cpp @ 624 : Invalid device number 1, there are 0 devices connected.

**Comment by ipa-rmb** [comment]
The topics you are using seem to be mixed quality, /hd/image_color_rect for the image, /sd/points for the depth data. With the old Kinect model this was not possible. I do not know whether the Kinect2 allows for that. You might check whether you get data on these topics by running the driver and typing these two commands in two other terminals:
rostopic hz /kinect2/hd/image_color_rect
rostopic hz /kinect2/sd/points
If you get responses (number of images published per second) for both command simultaneously, then your camera delivers the data in mixed quality. Otherwise try with
rostopic hz /kinect2/sd/image_color_rect
rostopic hz /kinect2/sd/points
If this works simultaneously, then you need to change the utilized topics in the people_detection.launch file.

Once you are sure that your camera provides images and point clouds simultaneously, please also check whether you receive responses on these commands:
rostopic hz /cob_people_detection/sensor_message_gateway/pointcloud_rgb_out
rostopic hz /cob_people_detection/sensor_message_gateway/colorimage_out
Please let me know the results of these checks.

By the way, you never need to start the openni or openni2 driver. The quick start instructions just give an example how to start the respective drivers for the old kinect models. Just start the iai_kinect2 drivers in your case.

**Comment by robotsorcerer** [comment]
Output from <pre class="terminal"><code>$ rostopic hz /kinect2/hd/image_color_rect</code></pre>

> subscribed to [/kinect2/hd/image_color_rect]
> average rate: 30.029
>     min: 0.031s max: 0.035s std dev: 0.00139s window: 9
> average rate: 29.993
>     min: 0.031s max: 0.036s std dev: 0.00122s window: 39

Output from <pre class="terminal"><code>$ rostopic hz /kinect2/hd/points</code></pre>

> WARNING: topic [/kinect2/hd/points] does not appear to be published yet

Output from <pre class="terminal"><code>$ rostopic hz /kinect2/sd/image_color_rect </code></pre>

> subscribed to [/kinect2/sd/image_color_rect]
> average rate: 30.045
>     min: 0.029s max: 0.037s std dev: 0.00183s window: 20
> average rate: 30.016
>     min: 0.019s max: 0.046s std dev: 0.00339s window: 50
> average rate: 30.005
> ...                    ...                        ...                                    ...                                 ...

Output from <pre class="terminal"><code>$ rostopic hz /kinect2/sd/points</code></pre>

> WARNING: topic [/kinect2/hd/points] does not appear to be published yet

Output from <pre class="terminal"><code>$ rostopic hz /cob_people_detection/sensor_message_gateway/intcloud_rgb_out
</code></pre>

> WARNING: topic [/cob_people_detection/sensor_message_gateway/pointcloud_rgb_out] does not appear to be published yet

Output from <pre class="terminal"><code>$ rostopic hz /cob_people_detection/sensor_message_gateway/colorimage_out
</code></pre>

> WARNING: topic [/cob_people_detection/sensor_message_gateway/colorimage_out] does not appear to be published yet

**Comment by ipa-rmb** [comment]
Ok, as long as your sensor does not deliver point cloud data, the people detection algorithm cannot do anything since it relies on that data.

Please setup your Kinect2 driver in a way that you get image AND point cloud topic simulatneously. You may request help from the developers of the iai_kinect2 driver package in doing so since I unfortunately do not have experience with it.

Once you get data on both sensor topics you may try again with my program.

**Comment by robotsorcerer** [comment]
oh <pre class="terminal" <code>$ rosrun kinect2_viewer kinect2_viewer sd cloud </code></pre> does deliver point cloud and image topics simultaneously. I did not know that was what this was all about.

**Comment by ipa-rmb** [comment]
Ok good. So if you get both data streams (image, point cloud), then people detection should run as well.

**Comment by robotsorcerer** [comment]
FaceRecognizer cannot open tdata.xml. I looked into the directory and it seems the tdata is not there.

> ---
> 
> ## Face Capture Node Parameters:
> 
> data_directory = /home/lex/.ros/cob_people_detection/files/
> norm_size = 100
> process[cob_people_detection/coordinator/coordinator-9]: started with pid [27737]
> norm_illumination = 1
> norm_align = 0
> norm_extreme_illumination = 0
> debug = 0
> use depth: 0
> Error: FaceRecognizer::loadTrainingData: Can't open /home/lex/.ros/cob_people_detection/files/training_data/tdata.xml.
> 
> ---
> 
> ## Coordinator Node Parameters:
> 
> namespace_gateway = /cob_people_detection/sensor_message_gateway/sensor_message_gateway
> CoordinatorNode initialized.
> FaceCaptureNode initialized. 0 color images and 0 depth images for training loaded.
> 
> ---
> 
> ## Sensor Message Gateway Parameters:
> 
> target_publishing_rate = 5
> display_timing = 0
> [ INFO] [1436461236.687127289]: Reconfigure request accomplished. New target publishing rate: 100.000000
> SensorMessageGatewayNode initialized.
> [ WARN] [1436461340.200261228]: Left-clicking no longer saves images. Right-click instead.

**Comment by ipa-rmb** [comment]
Have you trained any faces, yet? If not, there is no training data there, yet. Training data is stored in the tdata.txt file. Hence this is not really an error but rather a warning. Once you have trained two faces it should disappear on next startup. Just trust the quick start instructions and it will work. By the way, it is important to train 2 faces right at the beginning (required by the LDA algorithms), or to use a different algorithm.

**Comment by robotsorcerer** [comment]
I made a face detector and eye tracker based on opencv haar classifiers with the [libfreenect2](https://github.com/OpenKinect/libfreenect2) and [iai_kinect2](https://github.com/code-iai/iai_kinect2/) code . The code is [here](https://github.com/lakehanne/iai_kinect2/tree/master/kinect2_viewer). It's pretty rusty at the moment giving eye center coordinates for both eyes with respect to the depth -> color registration frame and putting a bounding rectangular box around the face. Ultimately, my goal would be to put a mesh similar to [this](https://youtu.be/jE-gftsaXb8) and get a more robust face tracker irrespective of race, age, face cosmetics and occlusion. 
Thnks for your help all along along! _Necessity is the mother of invention, eh?_
