### ISSUE TITLE
Cob_People_Detection Display and Client not working

### ISSUE THREAD

**Issue by bachapk** [ipa320/cob_people_perception#40]
When first time I installed these cob_people packages, everything worked well. But due to some reason it is not working at all. When I run : roslaunch cob_people_detection people_detection.launch OR roslaunch cob_people_detection people_detection.launch using_nodelets:=true it shows nothing in the display window. The display window is like this: 
![screenshot from 2016-05-30 14 02 47](https://cloud.githubusercontent.com/assets/19236442/15651587/1cfbd168-26b3-11e6-936c-6f0b393fe039.png)
It shows an error : **[ERROR] [1464618029.566038590]: Recognition model not trained**

Please note that roslaunch openni_launch openni.launch depth_registration:=true working perfectly and loading drivers successfully. Also kinect is connected.
Also when I write this command: rosrun cob_people_detection people_detection_client then it says No connection to server 'load_model_server'. 
![screenshot from 2016-05-30 14 03 37](https://cloud.githubusercontent.com/assets/19236442/15651600/2b5b8b36-26b3-11e6-83ba-f039699a0e71.png)
I am new. Please help what is wrong. My /home/bacha/catkin_ws/src/cob_people_perception/cob_people_detection/common/files/training_data folder is empty.
Bacha

**Comment by srinivasnisha** [comment]
I had a similar problem. You have to run roslaunch cob_people_detection people_detection.launch in one terminal and rosrun cob_people_detection people_detection_client on another terminal (Both have to be open). 

Terminal 1: roscore
Terminal 2: roslaunch openni_launch openni.launch
Terminal 3 : (source /devel/setup.bash) roslaunch cob_people_detection people_detection.launch (make sure  you are able to view the image and visualize the bounding boxes)
Terminal 4: (source /devel/setup.bash) and then rosrun cob_people_detection people_detection_client

Hopefully this works for you.

-Nisha

**Comment by bachapk** [comment]
Thank you for the reply. I was running every launch statement in separate terminal. Actually the issue was that in the cob_people_detection/ros/launch/face_recognizer_params.yaml file, The recognition_method was set to 2 (LDA2D) which required atleast 2 person's training data whether I had only one person training data. That was the reason I was not able to see any image when running roslaunch cob_people_detection people_detection.launch. It was mentioned in ( http://wiki.ros.org/cob_people_detection ) that "If you quit the program before recording a second person, the program might not start anymore."
To Resolve this issue I set recognition_method = 1 and now the launch statements running without any issue.
Thank you

**Comment by ipa-rmb** [comment]
Sorry for the trouble you had and the late reply due to my holidays. I hope the software now runs smoothly and is helpful to you.

**Comment by ateemawek** [comment]
i've the same proble and i tried to solved setting the recognition_method=1 but doesnt work, the window continue show the same problem
