### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by srinivasnisha** [ipa320/cob_people_perception#41]
I had a few questions on executing cob_people_detection. I was easily able to follow the wiki ros tutorial and get the face detection and recognition working. However, I could not figure out how to do tracking? Could you help me with it.

I also tried to run the leg_detector individually and nothing really happened. I followed the following process to run the leg detector,

Terminal 1: roscore
Teminal 2: roslaunch openni_launch openni.launch
terminal 3: roslaunch cob_leg_detector leg_detector.launch.

And nothing really happened. Am I supposed to visualize it in a different way?

And my last question is how do I get the 3D coordinates of the face detected? 

I would be really grateful if you could help me out. I am new to ROS and am not able to completely wrap my head around it.

Thank you,
Nisha

**Comment by ipa-rmb** [comment]
Sorry for the late reply, I was on vacation. I will have a look for the usage instructions with the tracking stuff tomorrow and let you know.

**Comment by ipa-rmb** [comment]
Alright, I have found the documentation for the leg detector and it is now online here: http://wiki.ros.org/cob_leg_detection . I did not try it out but please let me know if any information is missing.

Next, we have to figure out whether you want to use the tracking of detected faces over time - this is part of cob_people_detection and just happens all the time automatically by keeping probabilities of detected people from frame to frame. I.e. if you turn away from the camera but your head is still detected, your name will still display on your head (face not visible) until you leave the image. That is one tracker.

The other tracker is the leg detector and leg tracker. I hope the documentation posted above is helpful in using this. However, you need a robot with a laser scanner for using this software and you especially need to adapt your topic names. Anyways, we also refer to the original package for leg tracking, so maybe you find something useful there if you need it.

What concerns your last question, please checkout the detection_tracker/face_positions_array topic of type DetectionArray . Each Detection should contain the face's 3d coordinates in the camera frame within the pose.position.x / y / z properties. Easiest way to display this is rostopic echo detection_tracker/face_positions_array .
