### ISSUE TITLE
Package Installation too invasive

### ISSUE THREAD

**Issue by ipa-rmb** [ipa320/cob_people_perception#45]
Originally issued by RoboEvangelist in the wrong repository, see here https://github.com/ipa320/cob_perception_common/issues/63 .

Folks,

I installed the package, but it overridden my NiTE1.x installations, and also changed the paths in my cmake_prefix_path environment variable. Now I cannot run my other packages, even after uninstalling the cob_\* package.
I wonder if there is a way to install the NiTE2 from this repository in a local way so that it does not affect the rest of the package in ROS? By this I mean no Make/CMakeList hacking required from the user point of view. Or at least give the option to the user to install it locally, or globally. I don't think it's that difficult to do that.

Other than that, the face detection is pretty cool!

Thanks,

**Comment by ipa-rmb** [comment]
Hi,

Can you please specify how you installed cob_people_perception? By downloading from git and catkin_make (and catkin_make install)?
For now, I can only see one reason why you still cannot access the older version after uninstalling cob_\* . There is one bash script (https://github.com/ipa320/cob_people_perception/blob/indigo_dev/cob_openni2_tracker/launch/create_nite2_link.bash) that creates a link to NiTE2 during compilation in your .ros folder. This is necessary for openni2_tracker to run - we cannot change the library names in those binaries. Try to delete that link which should be located in $HOME/.ros/NiTE2.

Furthermore, if you downloaded the software package from github and if you do not need the oppeni2_tracker, then you can simply drop a CATKIN_IGNORE file into the cob_openni2_tracker and libnite2 packages and they won't be built and won't install a different NiTE version.

I fear that I will not be able to contribute a principled solution to this problem within the next weeks due to other work. If you find a simple way you are more than welcome to share that solution with us.

Best regards,
Richard

**Comment by RoboEvangelist** [comment]
I'll be working on this to make more comfortable in my system since I have other workspace and sensors and packaged that do get confused when I install Nite2 globally in catkin.
I found a work around, but it is quite manual. I'll let you know if this can be done better. Thanks

**Comment by RoboEvangelist** [comment]
This issue is solved, I think it can be closed
