### ISSUE TITLE
Can't See Published TF From Body Parts

### ISSUE THREAD

**Issue by RoboEvangelist** [ipa320/cob_people_perception#46]
Folks,

Why can't I see the joints being published? It's tracking the user, but I cannot see anything in the "rostopic echo tf..."

When I do "rosrun rqt_tf_tree rqt_tf_tree" I only see the camera links. Why not the transforms?

**Comment by ipa-rmb** [comment]
Hi, there is no tf publisher in the software. Recognized people are published in the cob_perception_msgs::DetectionArray format which contains pose information of the center of the face, name of the person etc. We simply did not need tf in this task so far, but if I get a student working on this package again, I will let him implement that feature.

**Comment by RoboEvangelist** [comment]
Yet, I see that the TF publisher code is already written in your cob_oppeni2 tracker package. It just does not seem to be activated. If I make it work, can I send a pull request? Otherwise not having a TF publisher kind of defeats the purpose of calling it a "tracker."

Thanks for your quick response.

**Comment by RoboEvangelist** [comment]
Never mind. It turns out the code is working, it is just activated through a parameter. Sorry for the confusion. Thanks for the work you've done with this package. Saved me a lot of time!

**Comment by ipa-rmb** [comment]
Alright, excellent. There is a second tracker in cob_people_detection for the tracking of detected faces over several frames. I thought you meant that one. The face tracker does indeed not publish to tf but it is a good idea to add this feature in future.

**Comment by ZuyuanZhu** [comment]
> Never mind. It turns out the code is working, it is just activated through a parameter. Sorry for the confusion. Thanks for the work you've done with this package. Saved me a lot of time!

Hi Luis,
Could you tell me how to turn on the tracker through the parameter? I am not familiar with the package at the moment. 
Many thanks!
Zuyuan
