### ISSUE TITLE
Cob_Openni2_Tracker Crashes After A certain amount of time

### ISSUE THREAD

**Issue by RoboEvangelist** [ipa320/cob_people_perception#47]
Folks,

I am running the cob_oppenni2_tracker, but it crashes after a certain amount of time. I pretty much the installation instructions with not modifications: [http://wiki.ros.org/cob_people_detection](http://wiki.ros.org/cob_people_detection).

I am using an Xtion sensor (the 640 x 480 resolution one) connected to USB 2.0. Any compatibility (or resource sharing) issues? Is it maybe an issue with running openni2_launch alongside cob_openni2_tracker nodes? A "Timeout" issues if a user is not found, perhaps?

This is the my entire error log I get (sorry if it's too long):

`[FATAL] [1468014962.668436134]: Failed to load nodelet '/camera/depth_points` of type `depth_image_proc/point_cloud_xyz` to manager `camera_nodelet_manager'
[FATAL] [1468014962.668452424]: Failed to load nodelet '/camera/rectify_color` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[FATAL] [1468014962.668610743]: Failed to load nodelet '/camera/depth_registered_rectify_depth` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[FATAL] [1468014962.670175538]: Failed to load nodelet '/camera/depth_registered_metric` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[FATAL] [1468014962.670253997]: Failed to load nodelet '/body_tracker` of type `cob_openni2_tracker/body_tracker_nodelet` to manager `/camera/camera_nodelet_manager'
[FATAL] [1468014962.670262776]: Failed to load nodelet '/camera/points_xyzrgb_hw_registered` of type `depth_image_proc/point_cloud_xyzrgb` to manager `camera_nodelet_manager'
[FATAL] [1468014962.670381691]: Failed to load nodelet '/camera/depth_metric_rect` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[camera/camera_nodelet_manager-2] process has died [pid 29688, exit code -11, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-camera_nodelet_manager-2.log].
log file: /home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-camera_nodelet_manager-2*.log
[camera/rectify_color-4] process has died [pid 29690, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=rgb/image_raw image_rect:=rgb/image_rect_color __name:=rectify_color __log:=/home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-rectify_color-4.log].
log file: /home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-rectify_color-4*.log
[camera/depth_registered_metric-12] process has died [pid 29755, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/convert_metric camera_nodelet_manager --no-bond image_raw:=depth_registered/image_raw image:=depth_registered/image __name:=depth_registered_metric __log:=/home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-depth_registered_metric-12.log].
log file: /home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-depth_registered_metric-12*.log
[body_tracker-17] process has died [pid 29810, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load cob_openni2_tracker/body_tracker_nodelet /camera/camera_nodelet_manager __name:=body_tracker __log:=/home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/body_tracker-17.log].
log file: /home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/body_tracker-17*.log
[camera/depth_metric_rect-6] process has died [pid 29698, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/convert_metric camera_nodelet_manager --no-bond image_raw:=depth/image_rect_raw image:=depth/image_rect __name:=depth_metric_rect __log:=/home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-depth_metric_rect-6.log].
log file: /home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-depth_metric_rect-6*.log
[camera/depth_points-8] process has died [pid 29721, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyz camera_nodelet_manager --no-bond image_rect:=depth/image_rect_raw points:=depth/points __name:=depth_points __log:=/home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-depth_points-8.log].
log file: /home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-depth_points-8*.log
[camera/depth_registered_rectify_depth-9] process has died [pid 29732, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=depth_registered/image_raw image_rect:=depth_registered/hw_registered/image_rect_raw __name:=depth_registered_rectify_depth __log:=/home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-depth_registered_rectify_depth-9.log].
log file: /home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-depth_registered_rectify_depth-9*.log
[camera/points_xyzrgb_hw_registered-10] process has died [pid 29742, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb camera_nodelet_manager --no-bond rgb/image_rect_color:=rgb/image_rect_color rgb/camera_info:=rgb/camera_info depth_registered/image_rect:=depth_registered/hw_registered/image_rect_raw depth_registered/points:=depth_registered/points __name:=points_xyzrgb_hw_registered __log:=/home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-points_xyzrgb_hw_registered-10.log].
log file: /home/luis/.ros/log/1630b54a-452d-11e6-8d96-90004e042890/camera-points_xyzrgb_hw_registered-10*.log`

**Comment by ipa-rmb** [comment]
Alright, I could reproduce the problem and modified the software a little bit. Apparently the openni2_launch+openni2_camera driver and the openni2_tracker can work together smoothly if the driver is started first, then both, camera image and point cloud are subscribed to, and then the openni2_tracker is started. If this order is kept, then all functions work perfectly together or individually.

I hence modified the launch file and the software for the tracker a bit. Please see the updated documentation on http://wiki.ros.org/cob_openni2_tracker (the major difference is that you have to start openni2_launch manually beforehand). The indigo_dev branch has already been updated be me, so please pull+build the current version before getting started. I tested it on two computers and never got any further problems.

**Comment by RoboEvangelist** [comment]
Groovy! Thanks.

**Comment by RoboEvangelist** [comment]
Hello,
I have a few questions, as I am a little confused:
Which sensor are you using with this ROS package? I have an Xtion Pro v0600. Do you need to install libopenn from command line as well for the pre-requisites or any other libraries? 
Also, in the instructions you mentioned to install Openni2.2, but openni2_camera already installs Openni2 for you. Are you suggesting to ignore the Openni2 that comes with openni2_camera and manually install the Openni2.2 that comes with structure io? Or it does not matter which one is used?
I asked this because the the program still crashes...not as often, but still does. I'm trying my own fixes as well on my side.
I get the following message when it crashes:

`[camera/camera_nodelet_manager-2] process has died [pid 13934, exit code -11, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/robot/.ros/log/36d9a216-5482-11e6-8f46-90004e042890/camera-camera_nodelet_manager-2.log].
log file: /home/robot/.ros/log/36d9a216-5482-11e6-8f46-90004e042890/camera-camera_nodelet_manager-2*.log
[camera/driver-3] process has finished cleanly
log file: /home/robot/.ros/log/36d9a216-5482-11e6-8f46-90004e042890/camera-driver-3*.log`

**Comment by ipa-rmb** [comment]
If you got libopenni2 already with the driver installation, it is fine. You just need that one. The instructions were a little bit too specific in the readme.md and I changed that.

Concerning your crashes, do you move your camera? I can remember that this caused the program to crash frequently some years ago. Maybe this has been fixed since then, though.

**Comment by RoboEvangelist** [comment]
By moving you mean physically? The camera is steady in the same spot. I think the problem is just related to the fact that there are two programs accessing the same hardware. We were thinking here on merging and having a single program that access all the necessary camera information at once.

**Comment by ipa-rmb** [comment]
Yes, I meant physically moving. Possibly, the problem is then indeed caused by having two programs that access too deep into the same hardware. Please let me know if you can succeed getting the two programs together into one program that accesses the hardware. We did not have enough resources to delve into that problem that deeply.

By the way, what is the time until your program crashes? For me it was stable for over 5 minutes today and I never observed any crashes after the last update. I have tried it with a 0600 and a 0601 Asus and it was always stable. 
Or do you change camera parameters via dynamic_recofigure in between? I did not try if this renders the software unstable.

**Comment by ipa-rmb** [comment]
Even changing the camera parameters with dynamic reconfigure was safely possible for me, as long as the image resolutions remain unchanged. If image res is varied, the program crashes, which is no surprise.

**Comment by RoboEvangelist** [comment]
I'm copying code from openni2_camera libraries into your package. So cob_openni2_tracker is now accessing video stream. So far I have not seen it crash, but only color images are being published right now. I'm gonna live it running all night long, and I'll see the log tomorrow morning. There is more evidence now that accessing the device from more than one programs seems to be the issue.
