### ISSUE TITLE
get rid of msh_dev

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_people_perception#67]
@ipa-fmw @ipa-rmb 
In order to be able to switch back to `indigo_dev` for MSH (and then removing `msh_dev`), there is only little changes needed...

1. According to https://github.com/ipa320/cob_people_perception/compare/indigo_dev...msh_dev?expand=1, the only relevant change in `msh_dev` is to [disable face_recognition](https://github.com/ipa320/cob_people_perception/blob/cf14f8c1a4ae5d6264be68015e833d9a1146311d/cob_people_detection/ros/launch/face_recognizer_params.yaml#L7). We could fix this by using our msh-specific yaml file

2. According to https://github.com/ipa320/cob_people_perception/compare/msh_dev...indigo_dev?expand=1, the only relevant change in `indigo_dev` that affects the MSH usecase is the [modified topic namespaces](https://github.com/ipa320/cob_people_perception/commit/630812225e3d244b3c8b54f118b752b83c24bf58). We could fix this by either making the topics non-global, so that the namespace could be modified **or** we adjust the namespaces in msh application

**Comment by fmessmer** [comment]
Regarding `2.`, the `people_detection_client` is not used in msh...thus, nothing from `indigo_dev`->`msh_dev` breaks msh-functionality...

**Comment by fmessmer** [comment]
Also regarding `1.`, the [change](https://github.com/ipa320/cob_people_perception/compare/indigo_dev...msh_dev?expand=1#diff-164afa6ac9a30cca07211d4cde916bd6R7) in the `face_recognizer_params.yaml` is only relevant to `face_recognizer.launch` which is part of `people_detection.launch` used in msh

However, the `people_detection.launch` starts a [ton of nodes](https://github.com/ipa320/cob_people_perception/blob/indigo_dev/cob_people_detection/ros/launch/people_detection.launch#L37-L47)...and I'm pretty sure, we do not actually use **all** of them

@ipa-fmw could you review this and filter the nodes that are actually required for msh-application?
Then we could call the relevant sub-launch files in `application.xml`....less nodes means less cpu load!

If we acctually rely on `face_recognizer.launch` I will then make it configurable via launch file args in order to use a msh-specific yaml.....then we can remove `msh_dev`

@ipa-fmw, let me know in case I missed some relevant changes in my summary above

**Comment by floweisshardt** [comment]
According to http://wiki.ros.org/cob_people_detection#Overview we use the chain up to `face_recognizer` where we use the topic `face_recognizer/face_recognitions`. We do not use 
- `detection_trigger`
- `coordinator`
- `face_capture_node`

**Comment by fmessmer** [comment]
@ipa-rmb 
I don't have the proper overview about this pipeline...maybe you could contribute a quick comment:
What do we gain by setting `enable_face_recognition` to `true`....or what do we lose if setting it to `false`?
All in the context of MSH where - according to @ipa-fmw - we only use the `face_recognizer/face_recognitions` topic...what effects does the `enable_face_recognition` parameter on this topic?
Is the information sent through the topic different when `enable_face_recognition` is set to `true` or does it just contain **additional** information?

**Comment by fmessmer** [comment]
PR #68 fixes the return value handling within `face_recognizer` in a way that still face_detections are published - labeled `UNKNOWN` - in case no recognition model could be loaded (because they are not available)
With this, we could use the `people_detection` for MSH without needing a special branch which only sets `enable_face_recognition` to false. @ipa-fmw

@ipa-rmb 
Maybe you could spare a few minutes tomorrow to discuss an even better configuration concept, i.e.
 - allow custom configuration from the "outside", i.e. allow overwrite of configs
 - allow to enable disable unused parts of the pipeline via launch arguments

**Comment by floweisshardt** [comment]
looks good. thanks @ipa-fxm for clarifying this

**Comment by fmessmer** [comment]
Merging #70 (which includes #69) solves this issue - adjustments in MSH are already tested on robot...
After merging, `msh_dev` can be deleted

thank you for your effort @ipa-rmb
