### ISSUE TITLE
Issue with running people detection on second machine.

### ISSUE THREAD

**Issue by quelotic** [ipa320/cob_people_perception#77]
I've exported the ROS_MASTER_URI on both computers and the ROS_HOSTNAME on each of them. Everything seems to be running fine with no errors. I have access on the depth and rgb images sent by the core machine, plus on the sensor_message_gateway image outputs. Still, nothing shows up on the image_view when running cob_people_detection.
I am running the astra camera (astra.launch) on the core machine.
And the people detection (people_detection.launch) on the second one.

**Comment by cagbal** [comment]
Did you change anything in people_detection.launch file? I am using the
code in second pc without any problem. Could you send the output of
rqt_graph?

Also, did you check the output of each node by writing:

- rostopic echo /head_detector/head_positions (for head detector node)
- rostopic echo /face_detector/face_positions (for face detector node)
- rostopic echo /face_recognizer/face_recognitions (for recognizer)
- rostopic echo /detection_tracker/face_position_array (for tracker)

For each of them, you should see an output even though there is no face or
head in the scene.

**Comment by quelotic** [comment]
The issue was resolved with a fresh compiling of the sources.
Nothing had been changed anyway, so I haven't figured out what the issue really was. And never had the problem since!
Thanks for the reply, closing the issue!
