### ISSUE TITLE
Fixing an error while executing "roslaunch cob_people_detection people_detection.launch"

### ISSUE THREAD

**Issue by amalgmar12** [ipa320/cob_people_perception#82]
Hi,
I amso intersted in your project . But I have a poblem , I will so grateful i you help me . firstely I run 
roslaunch openni_launch openni.launch device_id:=#2 an it is ok . Then I run "roslaunch cob_people_detection people_detection.launch" and I I have a problem .
System : elemeentary OS
Version Ros : kinetic 
Thank you for advance
![screenshot from 2018-06-12 18-46-10](https://user-images.githubusercontent.com/37368595/41307410-fc0902c0-6e70-11e8-8067-9e7ab61c1401.png)

**Comment by ipa-rmb** [comment]
If the program does not crash, this behaviour is totally fine. Please follow the tutorial instructions further and capture training images of two people and then create a recognition model. Then this warning will no further appear.

**Comment by amalgmar12** [comment]
Ok thank you so much .it works .
