### ISSUE TITLE
synchronize cob_people_detection/face_recognizer_node with tf/static_transform_publisher

### ISSUE THREAD

**Issue by amalgmar12** [ipa320/cob_people_perception#83]
Hi,
I am so interested in your project . I have a code for activity recognition using 3d body joints published by tf transformer (using openni tracker) .My goal is to try to  synchronize the output face and head position of your project with the skeleton extracted in my project . Can You help me please . Sorry for disturbing and thank you for advance .

**Comment by ipa-rmb** [comment]
Hi, I am currently not actively working on this package, so I will not have any time to support further developments. @cagbal : are you doing this already?

Anyways, ROS provides time synchronizers for receiving multiple messages. You should be able to find sufficient documentation on this.

**Comment by amalgmar12** [comment]
Hi,
ok , I will try to use time synchronizer . Please if you did any
improvement make me know . Thank you for your undrestanding.

2018-06-25 8:57 GMT+01:00 Richard Bormann <notifications@github.com>:

**Comment by ipa-rmb** [comment]
Sure.
