### ISSUE TITLE
tf message filter with cob_perception_msgs::ColorDepthImageArray

### ISSUE THREAD

**Issue by amalgmar12** [ipa320/cob_people_perception#84]
Hi,

I have a project for activities analysis and face recognition . I just link my project of activity recognition  which is subscribed to tf topic and the project of "cob_people_perception" but the problem is there no synchronization to link every skeleton with it's appropriate face. I will be so grateful if you help me how to synchronize tf topic with cob_perception_msgs::ColorDepthImageArray topic with tf:MessageFilter . Bellow is the code where I want to make synchronization .Thank you for advance . I try with this code in the file face_recognizer_node.cpp in main function but it shows unkown error .
[face_recognizer_node.cpp.zip](https://github.com/ipa320/cob_people_perception/files/2159900/face_recognizer_node.cpp.zip)

**Comment by ipa-rmb** [comment]
The following example should work, please consider all includes and definitions around the provided lines:
- https://github.com/ipa320/cob_people_perception/blob/68a0db77271f362d0c8ecd48db658e3b4e7ed841/cob_people_detection/ros/include/cob_people_detection/detection_tracker_node.h#L113
- https://github.com/ipa320/cob_people_perception/blob/68a0db77271f362d0c8ecd48db658e3b4e7ed841/cob_people_detection/ros/src/detection_tracker_node.cpp#L152

**Comment by amalgmar12** [comment]
ok  thank you so much much for your help  I will try it  .
